version: '3'

services:
  #mosquitto:
  #  container_name: eclipse-mosquitto
  #  image: eclipse-mosquitto
  #  restart: always
  #  ports:
  #    - '1883:1883'
  #    - '9001:9001'
  #  volumes:
  #    - ./MQTTBroker/mosquittodata:/data
  node-red:
    image: nodered/node-red:latest
    ports:
      - "1880:1880"
    volumes:
      - ./NodeRed/nodeRedData:/data
    restart: always
