version: '3'
services:
  mosquitto:
    container_name: eclipse-mosquitto
    image: eclipse-mosquitto
    restart: always
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - mosquittodata:/data
volumes:
  mosquittodata:
